export const START_SEARCH_REPOSITORIES = 'START_SEARCH_REPOSITORIES'
export const FETCH_SEARCH_REPOSITORIES = 'FETCH_SEARCH_REPOSITORIES'
export const ERROR_SEARCH_REPOSITORIES = 'ERROR_SEARCH_REPOSITORIES'
